package me.blockcast.common;

import java.io.File;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
* Op generated by hbm2java
*/
public class Post implements java.io.Serializable {

	private long id;
	private Location location;
	private double lat;
	private double lon;
	private String content;
	private long parentId;
	private long epoch;
	private long duration;
	private long distance;
	private int sec_remaining;
	private int sec_elapsed;
	private String media_name;
	private String media_preview;
	private File media_file;
	private String ip;
	private String guid;
	private int mine;
	
	public String getGuid() {
		return guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public Post() {}

	public Post(long id, Location location, String content, long parentId) {
		this.id = id;
		this.location = location;
		this.content = content;
		this.parentId = parentId;
	}

	public Post(long id, Location location, String content, long parentId, long epoch) {
		this.id = id;
		this.location = location;
		this.content = content;
		this.parentId = parentId;
		this.epoch = epoch;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public long getParentId() {
		return this.parentId;
	}

	public void setParentId(long parentId) {
		this.parentId = parentId;
	}

	public long getDistance() {
		return distance;
	}

	public void setDistance(long distance) {
		this.distance = distance;
	}

	public long getDuration() {
		return duration;
	}

	public void setDuration(long duration) {
		this.duration = duration;
	}

	public long getEpoch() {
		return this.epoch;
	}
	
	public void setEpoch(long epoch) {
		this.epoch = epoch;
	}
	
	public double getLon() {
		return lon;
	}

	public void setLon(double lon) {
		this.lon = lon;
	}

	public double getLat() {
		return lat;
	}

	public void setLat(double lat) {
		this.lat = lat;
	}
	public int getSec_remaining() {
		return sec_remaining;
	}

	public void setSec_remaining(int sec_remaining) {
		this.sec_remaining = sec_remaining;
	}

	public int getSec_elapsed() {
		return sec_elapsed;
	}

	public void setSec_elapsed(int sec_elapsed) {
		this.sec_elapsed = sec_elapsed;
	}

	public File getMedia_file() {
		return media_file;
	}

	public void setMedia_file(File mediafile) {
		this.media_file = mediafile;
	}

	public String getMedia_name() {
		return media_name;
	}

	public void setMedia_name(String medianame) {
		this.media_name = medianame;
	}
	
	public String getMedia_preview() {
		return media_preview;
	}

	public void setMedia_preview(String media_preview) {
		this.media_preview = media_preview;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public int getMine() {
		return mine;
	}

	public void setMine(int mine) {
		this.mine = mine;
	}
}
