package me.blockcast.web.pojo;

//Generated Feb 22, 2014 9:46:04 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
* Op generated by hbm2java
*/
public class Post implements java.io.Serializable {

	private long id;
	private Location location;
	private String content;
	private long parentId;
	private Date postTimestamp;
	private long duration;
	private long distance;

	public Post() {
	}

	public Post(long id, Location location, String content, long parentId) {
		this.id = id;
		this.location = location;
		this.content = content;
		this.parentId = parentId;
	}

	public Post(long id, Location location, String content, long parentId,
			Date postTimestamp) {
		this.id = id;
		this.location = location;
		this.content = content;
		this.parentId = parentId;
		this.postTimestamp = postTimestamp;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public long getParentId() {
		return this.parentId;
	}

	public void setParentId(long parentId) {
		this.parentId = parentId;
	}

	public Date getPostTimestamp() {
		return this.postTimestamp;
	}

	public void setPostTimestamp(Date postTimestamp) {
		this.postTimestamp = postTimestamp;
	}

	public long getDistance() {
		return distance;
	}

	public void setDistance(long distance) {
		this.distance = distance;
	}

	public long getDuration() {
		return duration;
	}

	public void setDuration(long duration) {
		this.duration = duration;
	}

}
